---
- name: Deploy web nginx config
  ansible.builtin.template:
    src: web.conf.j2
    dest: /etc/nginx/sites-available/web.conf
    mode: "0644"

- name: Enable web nginx config
  ansible.builtin.file:
    src: /etc/nginx/sites-available/web.conf
    dest: /etc/nginx/sites-enabled/web.conf
    state: link
    force: true

- name: Disable default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create html directory
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    mode: "0755"

- name: Create index page
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: "0644"

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
